### ISSUE TITLE
1.20 version requires Java 21

### ISSUE THREAD

**Issue by cassiancc** [Joel-Paul/Material-Beacons#6]
The 1.20.1 version of the mod requires Java 21, despite Minecraft 1.20 recommending the use of Java 17. If the mod does not actually require Java 21, lowering the requirement will help, as most launchers will automatically switch Java versions depending on the Minecraft version.

Worth noting, this especially affects users of Sinytra Connector, as Forge does not support mixins requiring the use of Java 21.

- [build.gradle](https://github.com/Joel-Paul/Material-Beacons/blob/main/build.gradle) compiling for Java 21.
- [fabric.mod.json](https://github.com/Joel-Paul/Material-Beacons/blob/main/src/main/resources/fabric.mod.json) requiring Java 21
- [mixins.json](https://github.com/Joel-Paul/Material-Beacons/blob/main/src/main/resources/material_beacons.mixins.json) requiring Java 21.

**Comment by Joel-Paul** [comment]
Ah shoot didn't catch that, thanks

**Comment by cassiancc** [comment]
Thanks for the quick fix!
